-- UPDATE TONGTIEN AFTER INSERT 1 ROW HOADONBH
CREATE OR REPLACE TRIGGER INSERT_HDBH
    BEFORE 
    INSERT  
    ON HOADONBH
    FOR EACH ROW    
DECLARE 
TONGTIEN NUMBER(10);
BEGIN
    SELECT CHIPHI_UT INTO TONGTIEN FROM PHIEUDANGKI WHERE MAPHIEU = :NEW.MAPHIEU;
    :NEW.TONGTIEN := TONGTIEN;
    :NEW.SOTIENCONLAI := TONGTIEN;
END;
/
-- UPDATE CHIPHI_UT AFTER INSERT CHI TIET PHIEU DANG KI
CREATE OR REPLACE TRIGGER INSERT_CTP_DK
    AFTER 
    INSERT  
    ON CT_PDKI
    FOR EACH ROW   
DECLARE
    GIA NUMBER(10);
BEGIN
    SELECT GIA INTO GIA FROM GOITIEM WHERE MAGOI = :NEW.MAGOI;
    UPDATE PHIEUDANGKI
    SET CHIPHI_UT = CHIPHI_UT + GIA*:NEW.SOLUONG
    WHERE MAPHIEU = :NEW.MAPHIEU;
    
END;
/
-- UPDATE CHIPHI_UT AFTER INSERT CHI TIET PHIEU DANG KI TIEM LE
CREATE OR REPLACE TRIGGER INSERT_CTP_DK_TL
    AFTER 
    INSERT  
    ON CT_PDK_TIEMLE
    FOR EACH ROW  
DECLARE 
    GIA NUMBER(10);
BEGIN
    SELECT GIA INTO GIA FROM VACXIN WHERE MAVX = :NEW.MAVX;
    UPDATE PHIEUDANGKI
    SET CHIPHI_UT = CHIPHI_UT + GIA*:NEW.SOLUONG
    WHERE MAPHIEU = :NEW.MAPHIEU;
    
END;
/
-- UPDATE TONG TIEN VA SO DOT THANH TOAN CUA HOA DON BAN HANG KHI THEM 1 CHI TIET DON BAN
CREATE OR REPLACE TRIGGER INSERT_CT_HDBH
    BEFORE
    INSERT  
    ON CT_DONBAN
    FOR EACH ROW 
DECLARE 
DOT NUMBER(10);
BEGIN
    SELECT SODOT_TT INTO DOT FROM HOADONBH WHERE  MAHDBH = :NEW.MAHD;
    :NEW.DOT :=DOT+1;
    UPDATE HOADONBH
    SET SODOT_TT = SODOT_TT +1, SOTIENCONLAI = SOTIENCONLAI - :NEW.SOTIEN
    WHERE MAHDBH = :NEW.MAHD;
END;
/
-- UPDATE TONG TIEN  CUA HOA DON DAT HANG KHI THEM 1 CHI TIET DON MUA
CREATE OR REPLACE TRIGGER INSERT_CT_HDDH
    AFTER 
    INSERT  
    ON CT_DONMUA
    FOR EACH ROW 
DECLARE 
    GIA NUMBER(10);
BEGIN
    SELECT GIA INTO GIA FROM VACXIN WHERE MAVX = :NEW.MAVX;
    UPDATE HOADONDH 
    SET TONGTIEN =  TONGTIEN + GIA*:NEW.SOLUONG
    WHERE MAHDDH = :NEW.MAHDDH;
END;
/
-- UPDATE TONG TIEN  CUA HOA DON DAT HANG KHI XOA 1 CHI TIET DON MUA
CREATE OR REPLACE TRIGGER DELETE_CT_HDDH
    AFTER 
    DELETE 
    ON CT_DONMUA
    FOR EACH ROW   
DECLARE 
    GIA NUMBER(10);
BEGIN
    SELECT GIA INTO GIA FROM VACXIN WHERE MAVX = :OLD.MAVX;
    UPDATE HOADONDH 
    SET TONGTIEN =  TONGTIEN - GIA*:OLD.SOLUONG
    WHERE MAHDDH = :OLD.MAHDDH;
END;
/
-- UPDATE TONG TIEN  CUA GOI TIEM KHI THEM 1 CHI TIET GOITIEM
CREATE OR REPLACE TRIGGER INSERT_CT_GT
    AFTER 
    INSERT  
    ON CTGT
    FOR EACH ROW  
DECLARE 
    GIAVX NUMBER(10);
BEGIN
    UPDATE GOITIEM 
    SET SLVACXIN = SLVACXIN +1
    WHERE MAGOI = :NEW.MAGOI;
    SELECT GIA INTO GIAVX FROM VACXIN WHERE MAVX = :NEW.MAVX;
    
    UPDATE GOITIEM G
    SET GIA = GIA + GIAVX*:NEW.SOLUONG
    WHERE MAGOI = :NEW.MAGOI;
END;
/
