-- TABLE LOAI NHAN VIEN
CREATE TABLE lOAINV 
(
    MALOAI NUMBER PRIMARY KEY,
    TENLOAI NVARCHAR2(50) NOT NULL
);
-- TABLE TRUNG TAM
CREATE TABLE TRUNGTAM 
(
   MATT NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
   TENTT NVARCHAR2(50) NOT NULL,
   DIACHI NVARCHAR2(50) NOT NULL,
   SDT VARCHAR(11)
);
-- TABLE KHACH HANG
CREATE TABLE KHACHHANG 
(
   MAKH NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
   HOTEN NVARCHAR2(50) NOT NULL,
   DIACHI NVARCHAR2(50) NOT NULL,
   SDT VARCHAR(11),
   EMAIL VARCHAR(50) NOT NULL,
   GIOITINH CHAR(1)  DEFAULT 'M' CHECK (GIOITINH IN ('M', 'F')) ,
   NGAYSINH DATE
);
-- TABLE NHA CUNG CAP 
CREATE TABLE NHACUNGCAP 
(
   MANCC NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
   TENNCC NVARCHAR2(50) NOT NULL,
   DIACHI NVARCHAR2(50) NOT NULL,
   SDT VARCHAR(11)
);
--TABLE GOI TIEM
CREATE TABLE GOITIEM 
(
   MAGOI NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
   TENGOI NVARCHAR2(50) NOT NULL,
   SLVACXIN NUMBER DEFAULT 0 CHECK (SLVACXIN >= 0) ,
   GIA NUMBER DEFAULT 0 CHECK (GIA >= 0)
);
-- TABLE NHAN VIEN 
CREATE TABLE NHANVIEN 
(
   MANV NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
   HOTEN NVARCHAR2(50) NOT NULL,
   DIACHI NVARCHAR2(50) NOT NULL,
   SDT VARCHAR(11),
   EMAIL VARCHAR(50) NOT NULL,
   GIOITINH CHAR(1) DEFAULT 'M' CHECK (GIOITINH IN ('M', 'F')),
   NGAYSINH DATE,
   BANGCAP VARCHAR(50),
   LUONG NUMBER(10) DEFAULT 10000000 CHECK (LUONG >= 0),
   MALOAINV NUMBER NOT NULL,
   MATT NUMBER NOT NULL,
   FOREIGN KEY (MALOAINV) REFERENCES LOAINV(MALOAI),
   FOREIGN KEY (MATT) REFERENCES TRUNGTAM(MATT)
);
-- TABLE ACCOUNT
CREATE TABLE ACCOUNT
(
    USERNAME VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(20) DEFAULT '1234',
    MANV NUMBER NOT NULL,
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
-- TABLE NGUOI GIAM HO
CREATE TABLE NGUOIGIAMHO 
(
   MAKH NUMBER,
   HOTEN NVARCHAR2(50) NOT NULL,
   QUANHE NVARCHAR2(50) NOT NULL,
   SDT VARCHAR(11),
   PRIMARY KEY (MAKH, SDT),
   FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);
-- TABLE VACXIN
CREATE TABLE VACXIN 
(
   MAVX NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
   MANCC NUMBER NOT NULL,
   TENVX NVARCHAR2(50) NOT NULL,
   LOAIVX NVARCHAR2(50) NOT NULL,
   SOLUONG NUMBER(10) DEFAULT 99 CHECK (SOLUONG >= 0),
   GIA NUMBER(10) DEFAULT 250000 CHECK (GIA >= 0),
   FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);
-- TABLE VACXIN TAI TRUNG TAM
CREATE TABLE VXTT
(
  MATT NUMBER NOT NULL,
  MAVX NUMBER NOT NULL,
  SOLUONG NUMBER DEFAULT 99 CHECK (SOLUONG >= 0),
  PRIMARY KEY (MATT, MAVX),
  FOREIGN KEY (MATT) REFERENCES TRUNGTAM(MATT),
  FOREIGN KEY (MAVX) REFERENCES VACXIN(MAVX)
);
-- TABLE CHI TIET GOI TIEM
CREATE TABLE CTGT
(
  MAGOI NUMBER NOT NULL,
  MAVX NUMBER NOT NULL,
  SOLUONG NUMBER DEFAULT 0 CHECK (SOLUONG >= 0),
  PRIMARY KEY (MAGOI, MAVX),
  FOREIGN KEY (MAGOI) REFERENCES GOITIEM(MAGOI),
  FOREIGN KEY (MAVX) REFERENCES VACXIN(MAVX)
);
-- TABLE PHIEU DANG KI
CREATE TABLE PHIEUDANGKI
(
    MAPHIEU NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
    MAKH NUMBER NOT NULL,
    MANVLAP NUMBER NOT NULL,
    LOAIDV  NUMBER DEFAULT 0 CHECK (LOAIDV IN (0,1)),
    NGAYMUONTIEM DATE NOT NULL,
    CHIPHI_UT NUMBER DEFAULT 0 CHECK (CHIPHI_UT >= 0),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MANVLAP) REFERENCES NHANVIEN(MANV)
);
-- TABLE CHI TIET PHIEU DANG KI
CREATE TABLE CT_PDKI
(
    MAPHIEU NUMBER NOT NULL,
    MAGOI NUMBER NOT NULL,
    SOLUONG NUMBER DEFAULT 0 CHECK (SOLUONG >= 0),
    PRIMARY KEY (MAPHIEU, MAGOI),
    FOREIGN KEY (MAPHIEU) REFERENCES PHIEUDANGKI(MAPHIEU),
    FOREIGN KEY (MAGOI) REFERENCES GOITIEM(MAGOI)
);
-- TABLE CHI TIET PHIEU DANG KI TIEM LE
CREATE TABLE CT_PDK_TIEMLE
(
    MAPHIEU NUMBER NOT NULL,
    MAVX NUMBER NOT NULL,
    SOLUONG NUMBER DEFAULT 0 CHECK (SOLUONG >= 0),
    PRIMARY KEY (MAPHIEU,MAVX),
    FOREIGN KEY (MAPHIEU) REFERENCES PHIEUDANGKI(MAPHIEU),
    FOREIGN KEY (MAVX) REFERENCES VACXIN(MAVX)
);
--TABLE HOA DON BAN HANG
CREATE TABLE HOADONBH 
(
    MAHDBH NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
    MAPHIEU NUMBER NOT NULL,
    MANVLAP NUMBER NOT NULL,
    LOAITHANHTOAN NUMBER DEFAULT 0 CHECK (LOAITHANHTOAN IN (0,1,2)),
    NGAYLAP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TINHTRANG NUMBER DEFAULT 0,
    TONGTIEN NUMBER(10) DEFAULT 0 CHECK (TONGTIEN >= 0),
    SODOT_TT NUMBER(10) DEFAULT 0 CHECK (SODOT_TT >= 0),
    SOTIENCONLAI NUMBER(10) DEFAULT 0 CHECK (SOTIENCONLAI >= 0),
    FOREIGN KEY (MAPHIEU) REFERENCES PHIEUDANGKI(MAPHIEU),
    FOREIGN KEY (MANVLAP) REFERENCES NHANVIEN(MANV)
);
-- TABLE 
CREATE TABLE CT_DONBAN
(
    MAHD NUMBER NOT NULL,
    MANVTHANHTOAN NUMBER NOT NULL,
    HINHTHUCTT NUMBER DEFAULT 0 CHECK (HINHTHUCTT IN (0,1,2)),
    SOTIEN NUMBER DEFAULT 0 CHECK (SOTIEN >= 0),
    DOT NUMBER DEFAULT 1 CHECK (DOT >= 1),
    NGAYTT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MAHD, NGAYTT),
    FOREIGN KEY (MAHD) REFERENCES HOADONBH(MAHDBH),
    FOREIGN KEY (MANVTHANHTOAN) REFERENCES NHANVIEN(MANV)
);
-- TABLE CA LAM
CREATE TABLE CALAM 
(
    MACA NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
    NGAYLAMVIEC DATE NOT NULL,
    CA NVARCHAR2(10) CHECK (CA IN (N'S',N'C', N'T')) NOT NULL,
    MAQL NUMBER NOT NULL,
    MATT NUMBER NOT NULL,
    FOREIGN KEY (MAQL) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MATT) REFERENCES TRUNGTAM(MATT)
);  
-- TABLE DANG KI CA LAM
CREATE TABLE DANGKICALAM
(
    MANV NUMBER NOT NULL,
    MACA NUMBER NOT NULL,
    PRIMARY KEY (MANV, MACA),
    FOREIGN KEY (MACA) REFERENCES CALAM(MACA),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
-- TABLE PHAN CONG
CREATE TABLE PHANCONG
(
    MANV NUMBER NOT NULL,
    MACA NUMBER NOT NULL,
    PRIMARY KEY (MANV, MACA),
    FOREIGN KEY (MACA) REFERENCES CALAM(MACA),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
--TABLE HOA DON DAT HANG
CREATE TABLE HOADONDH 
(
    MAHDDH NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
    MANVLAP NUMBER NOT NULL,
    MANVDUYET NUMBER NOT NULL,
    MATTNHAP NUMBER NOT NULL,
    NGAYLAP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    HINHTHUCTT NUMBER DEFAULT 0 CHECK (HINHTHUCTT IN (0,1)),
    TONGTIEN NUMBER DEFAULT 0 CHECK (TONGTIEN >= 0),
    TINHTRANG NUMBER DEFAULT 0 CHECK (TINHTRANG IN (0,1,2)),
    FOREIGN KEY (MANVLAP) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MANVDUYET) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MATTNHAP) REFERENCES TRUNGTAM(MATT)
);
-- TABLE CHI TIET DON DAT HANG
CREATE TABLE CT_DONMUA
(
    MAHDDH NUMBER NOT NULL,
    MAVX NUMBER NOT NULL,
    SOLUONG NUMBER DEFAULT 0 CHECK (SOLUONG >= 0),
    PRIMARY KEY (MAHDDH, MAVX),
    FOREIGN KEY (MAHDDH) REFERENCES HOADONDH(MAHDDH),
    FOREIGN KEY (MAVX) REFERENCES VACXIN(MAVX)
);